language: generic
sudo: required
services:
  - docker

before_install:
  # tag is internal so could be something simple like TESTME, but this is good practice
  - docker build -t draganglumac/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true draganglumac/docker-react yarn test

deploy:
  # force experimental version of deploy script to avoid missing bucket_name error
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-116810875000"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"