language: generic
sudo: required
services:
  - docker

before_install:
  # tag is internal so could be something simple like TESTME, but this is good practice
  - docker build -t draganglumac/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true draganglumac/docker-react yarn test